version: '3'
services:
    db:
        image: "postgres:11.7"
        ports:
            - "28041:5432"
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
        volumes:
            - c12-db-data-bsr:/var/lib/postgresql/data
            #- /home/docker/dev-BSR/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
        container_name: postgresql-12-ce-BSR
    odoo:
        image: "invosasystems/odoo-invosa:12.0"
        ports:
            - "8070:8069"
        volumes:
            - c12-odoo-data-bsr:/var/lib/odoo
            - /home/docker/dev-BSR/custom/ce12/:/mnt/extra-addons
            - /home/docker/dev-BSR/backups/ce12/:/mnt/odoo-backups
            - /home/docker/dev-BSR/logs/:/mnt/odoo-logs
            - /home/docker/dev-BSR/conf/odoo.conf:/etc/odoo/odoo.conf
        container_name: odoo-12-ce-BSR
        links:
            - db:db

volumes:
    c12-db-data-bsr:
    c12-odoo-data-bsr:

